### ISSUE TITLE
Support for other branch names

### ISSUE THREAD

**Issue by GrayJack** [vbrandl/hoc#159]
With a lot of people transitions away from `master`, it would be cool to be able to get hits of code for other branches names

**Comment by vbrandl** [comment]
I *think* (e.g. haven't actually tested) that it should work for any default branch, as long as it is configured as such. But I'll investigate.

Supporting non-default branches and multiple branches is already on my todo, but I didn't come up with a good concept yet, that doesn't end in race conditions and so on...

**Comment by GrayJack** [comment]
The sites keep complaining that it expect a master branch every time I try (I have 2 projects that have another default branch, I tested on those)

**Comment by vbrandl** [comment]
Can you link one of the repos with another default branch? I have an idea that I'll test later.

**Comment by GrayJack** [comment]
Sure! Here: https://github.com/GrayJack/janetrs

**Comment by vbrandl** [comment]
I implemented support for custom branches and refactored the local caching to support multiple branches per repository in c9a54eda493912db422a53e2f840428ddd0d4a65. 

Local test where looking good. Once CI passes and the Docker image is published, I'll deploy the changes on hitsofcode.com.

You can now request a specific branch by passing `?branch=dev` on any endpoint.

If you find any errors, please hit me up again :)

**Comment by GrayJack** [comment]
It's working perfectly!!! Thanks, I'll close the issue :smile:
