### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by yegor256** [vbrandl/hoc#21]
Would be great to have an ability to get the data in JSON format, not only as s badge.

**Comment by vbrandl** [comment]
Which fields would be interesting for the JSON output, besides the current head and the hoc?

**Comment by vbrandl** [comment]
You can now get the HoC result as JSON by appending `/json` to the request path: https://hitsofcode.com/github/vbrandl/hoc/json.

The result looks like this:

```json
{
  "head": "d609f9bf432921098f62c7dedae04a4c89ed04ef",
  "count": 7609
}
```

**Comment by yegor256** [comment]
@vbrandl this is exactly what I need, thanks!
