### ISSUE TITLE
Add support for projects hosted on sourcehut (sr.ht)

### ISSUE THREAD

**Issue by tsdh** [vbrandl/hoc#307]
Some testing suggests that hitsofcode.com supports projects hosted on github, gitlab, and bitbucket but not my project's which are on sourcehut. At least, when specifying a repository path such as https://hitsofcode.com/sourcehut/~tsdh/swayr or https://hitsofcode.com/srht/~tsdh/swayr, I get 404 page not foun.

The actual repository is https://git.sr.ht/~tsdh/swayr.

**Comment by vbrandl** [comment]
Sorry for the late reply. I just added `Sourcehut` as a supported service in https://github.com/vbrandl/hoc/releases/tag/v0.18.0

The overview page for your sourcehut repo is here: https://hitsofcode.com/sourcehut/~tsdh/swayr/view?branch=main

And here is the badge:

[![Hits-of-Code](https://hitsofcode.com/sourcehut/~tsdh/swayr?branch=main)](https://hitsofcode.com/sourcehut/~tsdh/swayr/view?branch=main)

**Comment by tsdh** [comment]
Thanks a lot!
