### ISSUE TITLE
500 error for some repo

### ISSUE THREAD

**Issue by g4s8** [vbrandl/hoc#31]
I'm trying to add HOC badge to my repo https://github.com/g4s8/matchers-json but it's not working: the badge is not displayed and the link is going to 500 error

the badge:
[![Hits-of-Code](https://hitsofcode.com/github/g4s8/matchers-json)](https://hitsofcode.com/view/github/g4s8/matchers-json)
source:
```md
[![Hits-of-Code](https://hitsofcode.com/github/g4s8/matchers-json)](https://hitsofcode.com/view/github/g4s8/matchers-json)
```

**Comment by vbrandl** [comment]
This seems to be an issue since v0.9.4. I just deployed the latest working version (v0.9.3) so the live deployment is working. I will now investigate the problem itself.

Thank you for reporting the issue!

**Comment by vbrandl** [comment]
The commit 7e13f93ee35bd6532b780c9af86cb2ab0ed54388 broke the build (updating of the dependency lock). I reverted the commit and published a new version that should work fine. After the CI pipeline finishes, I will deploy the latest version

**Comment by g4s8** [comment]
@vbrandl thanks!
