### ISSUE TITLE
total commits counter

### ISSUE THREAD

**Issue by yegor256** [vbrandl/hoc#33]
Would be great to receive the total amount of commits in the JSON response.

**Comment by vbrandl** [comment]
I just implemented this feature. The commit count is shown in the overview page and as a new field in the JSON response.

After the CI pipeline succeeds, I run the migration and update the deployment on hitsofocode.com

**Comment by vbrandl** [comment]
Migrating the cache somehow didn't work, so I deleted the cache. The next time, a badge is loaded might take a bit longer but everything else should be working:
https://hitsofcode.com/github/vbrandl/hoc/json
https://hitsofcode.com/view/github/vbrandl/hoc
