### ISSUE TITLE
Counting

### ISSUE THREAD

**Issue by Masynchin** [vbrandl/hoc#474]
Hello, @vbrandl!

I am struggling to understand what `count_repositories` function do:

https://github.com/vbrandl/hoc/blob/ecbc63f522653e4be76002b115bf8b85db37007d/src/count.rs#L4-L27

There are two issues:

1) What repositories this function counts? What is repository, if it is a directory path?
2) What is exact algorithm? I can see that function counts 5-level nested directories, but why? Why not 4 or 6-level nested? This number comes from some limitation?

I may want to refactor this function, if you would clarify these issues. Thanks!

**Comment by vbrandl** [comment]
That function is used for the "currently serving X repositories" stat in the footer. The total amount of repos that were queried using the service

**Comment by Masynchin** [comment]
> The total amount of repos that were queried using the service.

In what format are they saved? I don't understand why `count_repositories` counts nested directories like that.

**Comment by vbrandl** [comment]
The on disk layout for served repos is `<service>/<user>/<repo>` so to get the amount of repos, I just have to count everything in `*/*/*` to get the count

**Comment by Masynchin** [comment]
> Disk layout for served repos is `<service>/<user>/<repo>`

Thanks for explanation. So, I think this code can be simplified using [WalkDir](https://github.com/BurntSushi/walkdir):

~~~rust
trace!("Counting repositories"); 
std::fs::create_dir_all(&repo_path)?; 

WalkDir::new(repo_path)
    .min_depth(3)
    .max_depth(3)
    .into_iter()
    .filter(|entry| entry.file_type().is_dir())
    .count()
~~~

What do you think? If you are agree and this code works as I am expecting I can make a PR.

**Comment by vbrandl** [comment]
While WalkDir does look nice, I'm not sure, pulling in another dependency just for counting directories is worth doing.
I agree, the code could be tidied up, e.g. by deduplicating the `.filter(|entry| entry.file_type().map(|ft| ft.is_dir()).unwrap_or(false))` calls.
I have to look into WalkDir once I'm home again and give you a heads up.

**Comment by Masynchin** [comment]
> I'm not sure, pulling in another dependency just for counting directories is worth doing.

> The code could be tidied up, e.g. by deduplicating the `.filter(|entry| entry.file_type().map(|ft| ft.is_dir()).unwrap_or(false))` calls.

I came up with this pseudo solution:

~~~rust
iter::once(repo_path)
    .flat_map(sub_directories)
    .flat_map(sub_directories)
    .flat_map(sub_directories)
    .count()
~~~

This eliminates the need of adding another dependency. I will try not to bother you at your holidays. Cheers!

**Comment by vbrandl** [comment]
Your approach definitely looks better than the current implementation. I'd be open to review and merge a PR, if you are willing to give it a shot, or will implement it myself.

**Comment by Masynchin** [comment]
> I'd be open to review and merge a PR, if you are willing to give it a shot

Thanks, I am already have tested implementation, but also I will need your help. I am about to open a PR.
