### ISSUE TITLE
"hits of code" text in the badge

### ISSUE THREAD

**Issue by Hongbo-Miao** [vbrandl/hoc#545]
Currently the text in the badge is "Hits-of-Code". It would be great to allow customize or provide another version with text "hits of code" so that it can be consistent with other badges' style in https://shields.io/?

<img width="519" alt="image" src="https://user-images.githubusercontent.com/3375461/212532809-50261b6e-063f-4e05-ae8b-c6aa1026b7ad.png">

<img width="534" alt="image" src="https://user-images.githubusercontent.com/3375461/212532684-bda74594-02f0-40df-a828-aab0cb58fa95.png">

So it would look like

<img width="122" alt="image" src="https://user-images.githubusercontent.com/3375461/212533129-9f20e829-3c2c-4493-b316-0eb77fb6e301.png">

Thanks!

BTW, love the concept of hits of code! 😃

**Comment by vbrandl** [comment]
I just created https://github.com/vbrandl/hoc/pull/546 and will merge and release it, once the CI pipelines are finished.

I introduced a new `label` query parameter that can be used to customize the badge label. I also rudimentary documented the new parameter but I think the project is at a point where I have to overhaul the documentation, maybe add a dedicated documentation page.

I'll give you a heads up with an example query, once everything is released and deployed.

**Comment by Hongbo-Miao** [comment]
Thanks @vbrandl ! 🚀

**Comment by vbrandl** [comment]
I just deployed the new release. You can now use the new `label` parameter: https://hitsofcode.com/github/Hongbo-Miao/hongbomiao.com/view?branch=main&label=hits%20of%20code

This will show the markdown code to embed the badge with the chosen label.

**Comment by Hongbo-Miao** [comment]
You found the repo I am using. Haha, thanks! 👻
