### ISSUE TITLE
Now badges are not working

### ISSUE THREAD

**Issue by pomponchik** [vbrandl/hoc#746]
Hello! Thanks for your project! Now i see only text instead of badges.

**Comment by vbrandl** [comment]
Thanks for the heads up. I don't have time to look at the problem before tomorrow or Sunday but I'll try to add a testcase and fix the issue

**Comment by vbrandl** [comment]
Actually, do you have an example? The badge for this repo seems to work just fine: [![Hits-of-Code](https://hitsofcode.com/github/vbrandl/hoc?branch=master&label=Hits-of-Code)](https://hitsofcode.com/github/vbrandl/hoc/view?branch=master&label=Hits-of-Code)

**Comment by vbrandl** [comment]
Cannot reproduce
