### ISSUE TITLE
Implement proper overview page

### ISSUE THREAD

**Issue by vbrandl** [vbrandl/hoc#8]
Implement some kind of overview

**Comment by yegor256** [comment]
@vbrandl at least show some simple text, for now, saying that "This project has 777 hits of code"

**Comment by vbrandl** [comment]
@yegor256 I just implemented the overview page. Once the [CI pipeline](https://gitlab.com/vbrandl/hoc/pipelines/59011741) has finished, I will deploy the new version and you can have a look at it.

**Comment by yegor256** [comment]
@vbrandl thanks!
