### ISSUE TITLE
404 - Branch not Found on Rebuild cache

### ISSUE THREAD

**Issue by magdel** [vbrandl/hoc#833]
My project does not have master branch but main.
So when I click Rebuild cache I get 404.

I open https://hitsofcode.com/github/magdel/agloraemulator/view?branch=main&label=Hits-of-Code and click Rebuild cache.

![image](https://github.com/user-attachments/assets/29495760-44b1-4727-a6a1-0ddf8f6b9317)

I use badge at https://github.com/magdel/agloraemulator

**Comment by vbrandl** [comment]
Thanks for the bug report. I'm working on a fix and will release it soonish.
