### ISSUE TITLE
[proposal] passing some files to ignore

### ISSUE THREAD

**Issue by muturgan** [vbrandl/hoc#835]
Hello Valentin. Thank you for this great tool.
I recently started using it and noticed one thing. I was pushed a really tiny commit to my node.js project. But it contains a dependency updating. And my HoC score was increased on 5k points - a lock file contains too many changes.
I suggest adding a query parameter to the badge link containing files that will not be taken into account when calculating the score.

**Comment by vbrandl** [comment]
Hey @muturgan,

I already thought about that in https://github.com/vbrandl/hoc/issues/5 and just realized it has been more than 5 years ago...
I will think about how I can implement this feature.

**Comment by vbrandl** [comment]
Sure, any PR is welcome
